# Generated by Django 5.2 on 2025-04-20 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostGrad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Posto/Graduação')),
            ],
            options={
                'verbose_name': 'Post/Grad',
                'verbose_name_plural': 'Post/Grad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduta', models.CharField(blank=True, choices=[('SN', 'Sem Novidade'), ('CN', 'Com Novidade'), ('PN', 'Possível Novidade')], max_length=2, null=True, verbose_name='Conduta')),
                ('re', models.CharField(max_length=9, unique=True, verbose_name='R.E.')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('opm', models.CharField(blank=True, max_length=50, null=True, verbose_name='OPM')),
                ('subunidade', models.CharField(blank=True, choices=[('EM', 'Estado Maior'), ('1CIA', '1ª Cia'), ('2CIA', '2ª Cia'), ('3CIA', '3ª Cia'), ('4CIA', '4ª Cia'), ('OUTRA', 'Outra')], max_length=5, null=True, verbose_name='Subunidade')),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação')),
                ('consulta', models.TextField(blank=True, null=True, verbose_name='Consulta')),
                ('p2', models.TextField(blank=True, null=True, verbose_name='P2')),
                ('jd', models.TextField(blank=True, null=True, verbose_name='JD')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d/', verbose_name='Foto')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Atualizado em')),
                ('post_grad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policiais', to='inteligencia.postgrad', verbose_name='Post/Grad')),
            ],
            options={
                'verbose_name': 'Policial',
                'verbose_name_plural': 'Policiais',
                'ordering': ['post_grad__id'],
            },
        ),
    ]
