# Generated by Django 5.2 on 2025-04-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policial',
            name='post_grad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inteligencia.postgrad', verbose_name='Post/Grad'),
        ),
        migrations.CreateModel(
            name='PlanoChamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re', models.CharField(max_length=9, unique=True, verbose_name='R.E.')),
                ('nome_guerra', models.CharField(max_length=50, verbose_name='Nome de Guerra')),
                ('nome_completo', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('subunidade', models.CharField(choices=[('EM', 'Estado Maior'), ('1CIA', '1ª Cia'), ('2CIA', '2ª Cia'), ('3CIA', '3ª Cia'), ('4CIA', '4ª Cia'), ('OUTRA', 'Outra')], max_length=5, verbose_name='Subunidade')),
                ('situacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Situação')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('uf', models.CharField(choices=[('SP', 'São Paulo'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso\t'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais\t'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('celulares', models.CharField(max_length=50, verbose_name='Celulares')),
                ('telefone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone Residencial')),
                ('recado', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefones para Recado')),
                ('post_grad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inteligencia.postgrad', verbose_name='Post/Grad')),
            ],
            options={
                'verbose_name': 'Plano de Chamada',
                'verbose_name_plural': 'Plano de Chamada',
                'ordering': ['post_grad__id'],
            },
        ),
    ]
