# Generated by Django 5.2 on 2025-04-20 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia', '0002_alter_policial_post_grad_planochamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='planochamada',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planochamada',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='plano_chamada/%Y/%m/%d/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='planochamada',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='policial',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='nada-consta/%Y/%m/%d/', verbose_name='Foto'),
        ),
    ]
