# Generated by Django 5.2 on 2025-04-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inteligencia', '0003_planochamada_created_at_planochamada_imagem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policial',
            new_name='NadaCosta',
        ),
        migrations.AlterModelOptions(
            name='nadacosta',
            options={'ordering': ['post_grad__id'], 'verbose_name': 'Nada Costa', 'verbose_name_plural': 'Nada Costa'},
        ),
    ]
